// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtjsJExoEGT1dpyKSjKSVSSOk9283cA4',
    appId: '1:485314249034:web:d92fe7d693f326b76001b3',
    messagingSenderId: '485314249034',
    projectId: 'flutter-test-5f189',
    authDomain: 'flutter-test-5f189.firebaseapp.com',
    storageBucket: 'flutter-test-5f189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2a9wZCay3F-1r4EfDDXfj1FuPHVr9WP8',
    appId: '1:485314249034:android:74b6aad517d4ea9a6001b3',
    messagingSenderId: '485314249034',
    projectId: 'flutter-test-5f189',
    storageBucket: 'flutter-test-5f189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmtlg3ybjYgrqd_m3makRpA5ne2Cq56Do',
    appId: '1:485314249034:ios:c7c99c4648c4118f6001b3',
    messagingSenderId: '485314249034',
    projectId: 'flutter-test-5f189',
    storageBucket: 'flutter-test-5f189.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmtlg3ybjYgrqd_m3makRpA5ne2Cq56Do',
    appId: '1:485314249034:ios:c7c99c4648c4118f6001b3',
    messagingSenderId: '485314249034',
    projectId: 'flutter-test-5f189',
    storageBucket: 'flutter-test-5f189.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
